** WARNING: connection is not using a post-quantum key exchange algorithm.
** This session may be vulnerable to "store now, decrypt later" attacks.
** The server may need to be upgraded. See https://openssh.com/pq.html
** WARNING: connection is not using a post-quantum key exchange algorithm.
** This session may be vulnerable to "store now, decrypt later" attacks.
** The server may need to be upgraded. See https://openssh.com/pq.html
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: 
          - '192.168.30.23:9100'  # web1
          - '192.168.40.11:9100'  # web2
          - 'localhost:9100'      # сам prometheus

  - job_name: 'nginx_log_exporter'
    static_configs:
      - targets: 
          - '192.168.30.23:4040'  # web1
          - '192.168.40.11:4040'  # web2
