all:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/id_rsa_diploma
  
  children:
    bastion_servers:
      hosts:
        bastion:
          ansible_host: 89.169.134.145
    
    web_servers:
      hosts:
        web1:
          ansible_host: 192.168.30.23
          ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q ubuntu@89.169.134.145"'
        web2:
          ansible_host: 192.168.40.11
          ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q ubuntu@89.169.134.145"'
    
    prometheus_servers:
      hosts:
        prometheus:
          ansible_host: 192.168.30.3
          ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q ubuntu@89.169.134.145"'
    
    elasticsearch_servers:
      hosts:
        elasticsearch:
          ansible_host: 192.168.30.11
          ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q ubuntu@89.169.134.145"'
    
    grafana_servers:
      hosts:
        grafana:
          ansible_host: 89.169.191.199
    
    kibana_servers:
      hosts:
        kibana:
          ansible_host: 130.193.40.133
    
    bastion:
      children:
        bastion_servers:
    
    webservers:
      children:
        web_servers:
    
    monitoring:
      children:
        prometheus_servers:
        grafana_servers:
    
    logging:
      children:
        elasticsearch_servers:
        kibana_servers:
    
    private_servers:
      children:
        web_servers:
        prometheus_servers:
        elasticsearch_servers:
    
    public_servers:
      children:
        grafana_servers:
        kibana_servers:
    
    all_servers:
      children:
        web_servers:
        prometheus_servers:
        elasticsearch_servers:
        grafana_servers:
        kibana_servers:
