all:
  children:
    bastion_servers:
      hosts:
        bastion:
          ansible_host: 89.169.134.145
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa_diploma
    
    web_servers:
      hosts:
        web1:
          ansible_host: 192.168.30.23
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa_diploma
          ansible_ssh_common_args: '-o ProxyCommand="ssh -i ~/.ssh/id_rsa_diploma -W %h:%p -q ubuntu@89.169.134.145"'
        web2:
          ansible_host: 192.168.40.11
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa_diploma
          ansible_ssh_common_args: '-o ProxyCommand="ssh -i ~/.ssh/id_rsa_diploma -W %h:%p -q ubuntu@89.169.134.145"'
    
    prometheus_servers:
      hosts:
        prometheus:
          ansible_host: 192.168.30.3
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa_diploma
          ansible_ssh_common_args: '-o ProxyCommand="ssh -i ~/.ssh/id_rsa_diploma -W %h:%p -q ubuntu@89.169.134.145"'
    
    elasticsearch_servers:
      hosts:
        elasticsearch:
          ansible_host: 192.168.30.11
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa_diploma
          ansible_ssh_common_args: '-o ProxyCommand="ssh -i ~/.ssh/id_rsa_diploma -W %h:%p -q ubuntu@89.169.134.145"'
    
    grafana_servers:
      hosts:
        grafana:
          ansible_host: 89.169.191.199
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa_diploma
          ansible_ssh_common_args: '-o ProxyCommand="ssh -i ~/.ssh/id_rsa_diploma -W %h:%p -q ubuntu@89.169.134.145"'
    
    kibana_servers:
      hosts:
        kibana:
          ansible_host: 130.193.40.133 
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa_diploma
          ansible_ssh_common_args: '-o ProxyCommand="ssh -i ~/.ssh/id_rsa_diploma -W %h:%p -q ubuntu@89.169.134.145"'
